### PR TITLE
Feature/homework2

### PR DESCRIPTION
**Pull request by ikushlianski**
Implement in-memory CRUD REST service according to [requirements](https://epam.sharepoint.com/sites/EPAMNode.jsGlobalMentoringProgram/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FEPAMNode%2EjsGlobalMentoringProgram%2FShared%20Documents%2FGeneral%2FHomework%2FModule%202%2FHomework%202%2Epdf&parent=%2Fsites%2FEPAMNode%2EjsGlobalMentoringProgram%2FShared%20Documents%2FGeneral%2FHomework%2FModule%202&p=true&originalPath=aHR0cHM6Ly9lcGFtLnNoYXJlcG9pbnQuY29tLzpiOi9zL0VQQU1Ob2RlLmpzR2xvYmFsTWVudG9yaW5nUHJvZ3JhbS9FVFFmWUZzTkUwWlBzemZyUGx2RjY0SUIyNWtBV2NfaE02ZWpzZXVDX3pNaWVRP3J0aW1lPVZyR21aQmxHMkVn):
- set up Typescript and Express server
- implement CRUD methods
- add Joi validation

Note: User fields are required only during create (`login`, `password`, `age`). During update, as in a real-life project, all fields are optional and `id` cannot be modified.

### CODE REVIEW

**Review by akuchynski — CHANGES_REQUESTED** [review]
[Recommendation] The previous task folder can be excluded from the current branch. Also, as discussed on our Q&A session it's better to rename 'task-1' to 'core' and 'task-2' to 'api'.

**Comment by akuchynski** [comment]
> Implement in-memory CRUD REST service according to [requirements](https://epam.sharepoint.com/sites/EPAMNode.jsGlobalMentoringProgram/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FEPAMNode%2EjsGlobalMentoringProgram%2FShared%20Documents%2FGeneral%2FHomework%2FModule%202%2FHomework%202%2Epdf&parent=%2Fsites%2FEPAMNode%2EjsGlobalMentoringProgram%2FShared%20Documents%2FGeneral%2FHomework%2FModule%202&p=true&originalPath=aHR0cHM6Ly9lcGFtLnNoYXJlcG9pbnQuY29tLzpiOi9zL0VQQU1Ob2RlLmpzR2xvYmFsTWVudG9yaW5nUHJvZ3JhbS9FVFFmWUZzTkUwWlBzemZyUGx2RjY0SUIyNWtBV2NfaE02ZWpzZXVDX3pNaWVRP3J0aW1lPVZyR21aQmxHMkVn):
> 
> * set up Typescript and Express server
> * implement CRUD methods
> * add Joi validation
> 
> Note: User fields are required only during create (`login`, `password`, `age`). During update, as in a real-life project, all fields are optional and `id` cannot be modified.

Could you please put a short overview of this task to README file?

**Comment by ikushlianski** [comment]
> [Recommendation] The previous task folder can be excluded from the current branch. Also, as discussed on our Q&A session it's better to rename 'task-1' to 'core' and 'task-2' to 'api'.

I will rename `task-1` to core, and all further tasks including task2 will go under `src`

**Review by akuchynski — APPROVED** [review]
All tasks completed, all comments has been resolved.

**Pull request merged**
